// Generated by nuxi
/// <reference types="@vueuse/nuxt" />
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="nuxt-icon" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />

export {}
