// Generated by nuxi
/// <reference types="@vueuse/nuxt" />
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="nuxt-icon" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxtjs/google-fonts" />
/// <reference types="nuxt-swiper" />
/// <reference types="shadcn-nuxt" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="vite/client" />
/// <reference path="types/i18n-plugin.d.ts" />
/// <reference types="swiper/vue" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
